# Generated by Django 5.2.7 on 2026-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_booking_status_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='role_type',
            field=models.CharField(choices=[('USER', 'User'), ('GUEST', 'Guest')], max_length=10),
        ),
    ]
